    - name: Deploy Flask App via SSM
      run: >
        aws ssm send-command
        --document-name "AWS-RunShellScript"
        --region ${{ secrets.AWS_REGION }}
        --comment "Deploy Flask app"
        --instance-ids ${{ secrets.INSTANCE_IDS }}
        --parameters commands='[
          "mkdir -p /home/ec2-user/app",
          "cd /home/ec2-user/app",
          "aws s3 cp s3://${{ secrets.S3_BUCKET }}/app.zip .",
          "unzip -o app.zip",
          "chmod +x startup.sh",
          "./startup.sh"
        ]'
        --output text
